// mockData.ts
export const mockProducts = [
  {
    id: 1,
    name: "منتج رقم 1",
    store: "المتجر الأول",
    price: 200,
    discountedPrice: 150,
    rating: 4.5,
    reviews: 30,
    image: "/images/product1.jpg",
  },
  {
    id: 2,
    name: "منتج رقم 2",
    store: "المتجر الثاني",
    price: 250,
    discountedPrice: 180,
    rating: 4.2,
    reviews: 45,
    image: "/images/product2.jpg",
  },
  {
    id: 3,
    name: "منتج رقم 3",
    store: "المتجر الثالث",
    price: 100,
    discountedPrice: 90,
    rating: 4.7,
    reviews: 20,
    image: "/images/product3.jpg",
  },
  {
    id: 4,
    name: "منتج رقم 4",
    store: "المتجر الرابع",
    price: 300,
    discountedPrice: 250,
    rating: 4.9,
    reviews: 12,
    image: "/images/product4.jpg",
  },
  {
    id: 5,
    name: "منتج رقم 5",
    store: "المتجر الخامس",
    price: 150,
    discountedPrice: 100,
    rating: 4.0,
    reviews: 38,
    image: "/images/product5.jpg",
  },
  {
    id: 6,
    name: "منتج رقم 6",
    store: "المتجر السادس",
    price: 180,
    discountedPrice: 130,
    rating: 4.3,
    reviews: 25,
    image: "/images/product6.jpg",
  },
  {
    id: 7,
    name: "منتج رقم 7",
    store: "المتجر السابع",
    price: 320,
    discountedPrice: 270,
    rating: 4.6,
    reviews: 18,
    image: "/images/product7.jpg",
  },
  {
    id: 8,
    name: "منتج رقم 8",
    store: "المتجر الثامن",
    price: 400,
    discountedPrice: 350,
    rating: 4.8,
    reviews: 22,
    image: "/images/product8.jpg",
  },
];
export const offers = [
  // منتجات عروض اليوم
  {
    id: 1,
    name: "ساعة ذكية",
    store: "متجر التقنيات",
    price: 250,
    discountedPrice: 199,
    rating: 4.5,
    reviews: 123,
    image: "/images/products/watch.jpg",
  },
  {
    id: 2,
    name: "سماعات بلوتوث",
    store: "الصوت النقي",
    price: 150,
    discountedPrice: 99,
    rating: 4.2,
    reviews: 85,
    image: "/images/products/headphones.jpg",
  },
  // ... المزيد
];

export const bestSellers = [
  {
    id: 3,
    name: "لابتوب للألعاب",
    store: "ألعاب برو",
    price: 4500,
    discountedPrice: 3899,
    rating: 4.8,
    reviews: 200,
    image: "/images/products/laptop.jpg",
  },
  {
    id: 4,
    name: "جهاز عرض",
    store: "المنزل الذكي",
    price: 800,
    discountedPrice: 699,
    rating: 4.3,
    reviews: 64,
    image: "/images/products/projector.jpg",
  },
  // ... المزيد
];

export const selected = [
  {
    id: 5,
    name: "لوحة مفاتيح ميكانيكية",
    store: "كيبوردات",
    price: 300,
    discountedPrice: 275,
    rating: 4.6,
    reviews: 45,
    image: "/images/products/keyboard.jpg",
  },
  {
    id: 6,
    name: "ماوس ألعاب",
    store: "ألعاب برو",
    price: 120,
    discountedPrice: 99,
    rating: 4.4,
    reviews: 88,
    image: "/images/products/mouse.jpg",
  },
  // ... المزيد
];
